
using System;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
// CONVERT WARNING :Option Explicit statement is not implemented.
// CONVERT WARNING :Option Explicit statement is not implemented.
namespace My.Resources
{
	//StronglyTypedResourceBuilder generó automáticamente esta clase
	//a través de una herramienta como ResGen o Visual Studio.
	//Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	//con la opción /str o vuelva a generar su proyecto de VS.
	///<summary>
	///  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	internal class Resources
	{
		private global::System.Resources.ResourceManager resourceMan;
		private global::System.Globalization.CultureInfo resourceCulture;
		///<summary>
		///  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pasaportes.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		///<summary>
		///  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
	}
}
